### ISSUE TITLE
Catalogue Scraper

### ISSUE THREAD

**Issue by GenericConfluent** [GenericConfluent/finescale#3]
## Task
Build a command line tool that can fetch all the pages from the uAlberta catalogue website, and parse the courses as described in the motivation section.

Must meet the following requirements:
- Minimize load on UofA servers. On the first script run it's fine to send a web request for the web pages, but do the following:
  - Check $PWD for downloaded pages. If they are there skip the download and use the local copy
  - Don't send all the requests at the same time. Download the catalogue page for a single department, process that, and download the next.
  - If processing is surprisingly fast keep track of the time since the last request and add an artificial delay. Try not to do more than a request every 15s. (It's fine for this script to take a while to run. It only needs to be run a single time every once in a while to get course updates which don't happen all that often.)
- Segment and structure the information in each course listing: the course description should be stored as a separate field and most importantly the prereqs and coreqs should be nicely parsed so it's easy for the app to use.
- Serialize the parsed data to the disk so it can be used later on. This is somewhat flexible since the deserialization is yet to be implemented. I recommend serializing each department's catalogue as a separate file because it will allow for nicer updates later on (i.e. the CMPUT courses are all in one file, the MATH courses are all in one file, etc). If you end up using python:
  - [`pyron`](https://github.com/cswinter/pyron) would probably be nicer to deserialize on the rust end. But is an extra library to install.
  - The `json` module in python works just fine but it's a bit verbose.
  - The `pickle` is nice since it's a binary representation so it's dense. It's also possible to [deserialize in rust](https://crates.io/crates/serde-pickle) which is good. The only downside is that the processed files would then be hard to modify after they are created, which may make correcting mistakes made by the script a bit of a nightmare.

## Motivation
An app deals with simplifying the UofA course graph for people first need to know:

1. What the courses available are.
2. How they relate to each other.

For example, take [CMPUT 204 - Algorithms I](https://apps.ualberta.ca/catalogue/course/cmput/204). A program (script or binary) going through the HTML of the [CMPUT catalogue page](https://apps.ualberta.ca/catalogue/course/cmput) should be able to add it to the list of available courses and specify the connections to other courses from the description:

"The first of two courses on algorithm design and analysis, with emphasis on fundamentals of searching, sorting, and graph algorithms. Examples include divide and conquer, dynamic programming, greedy methods, backtracking, and local search methods, together with analysis techniques to estimate program efficiency. Prerequisites: CMPUT 175 or 275 and CMPUT 272; one of MATH 100, 113, 114, 117, 134, 144, 154, or SCI 100."

Whatever the solution is should be able to segment the description from the Prereq/Coreq spec and parse the prereqs and coreqs so they can be iterated over when doing actual processing in the app. The above should be turned into something like:
```
And [
    And [
        Or [ CMPUT 175, CMPUT 275 ],
        CMPUT 272
    ],
    Or [
        MATH 100,
        MATH 113,
        MATH 114,
        MATH 117,
        MATH 134,
        MATH 144,
        MATH 154,
        SCI 100
    ]
]
```
Which the in-memory graph can be much more easily constructed from. (Note that you would need to wrap stuff to distinguish between prereqs and coreqs, i.e. all of the course IDs above should be wrapped in `Prereq`, though that makes things less readable so I omitted it).

## Implementation
You'll notice a [`scraper`](https://github.com/GenericConfluent/finescale/tree/main/scraper) directory in the project root. You can ignore that. If you want to give this a go I would say the best way is probably to write a Python script using a language processing library or a ML model. Even if you aren't familiar with either of those things give it a go, learning is a bit of work but completely doable. Take a look at [spacy](https://spacy.io/), [NLTK](https://www.nltk.org/), [PyTorch](https://pytorch.org/), and [TensorFlow](https://www.tensorflow.org/). If you end up going the ML route fine tuning an open source model would probably work out best.

If you want to work in Rust, C, C++, Haskell, Kotlin, Java, Zig, etc. That's perfectly fine. I bring up Python because it requires minimal configuration, is widely available, has good library support, and is well known.

If you know what you're doing much better than I do you may also have other, better ideas. That also works fine.

**Comment by tadeokondrak** [comment]
I spent some time trying to parse the course requirements and treating it like a parsing problem similar to programming languages was working pretty well for a while.

After trying to get more tests passing, I'm realizing I probably want to solve this problem by using a parsing algorithm that can handle ambiguous languages and return multiple parse trees.

I'm going to try rewriting the parser to use a GLR parser generator: https://github.com/igordejanovic/rustemo. Hopefully this works better.
