### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by tadeokondrak** [GenericConfluent/finescale#9]
It would be nice to add an open-source license.

This is my understanding of the landscape:

- Zlib: Almost no restrictions
- ISC/MIT: Requires attribution for derived works
- MPL-2.0: Requires that, if this work is modified and becomes part of a larger work, that the modified files part of the original work have their source code published under the MPL
- GPL-3.0: Similar to MPL but requires the entire larger work to have its source code published under the GPL
- AGPL-3.0: Similar to the GPL but also applies when the user is accessing the larger work as a network service (like a website)

I like the MPL as a good balance here. Unlike with the GPL it shouldn't keep anyone from reusing the code.

**Comment by GenericConfluent** [comment]
I agree MPL seems good. Though I would also be fine with MIT.
